# Generated by Django 5.1.2 on 2024-10-26 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
