# Generated by Django 5.1.3 on 2024-12-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store1', '0002_remove_order_discount_remove_order_shipping_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
