# Generated by Django 5.1.2 on 2024-10-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store1', '0005_product_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='All',
            field=models.BooleanField(default=False),
        ),
    ]
