# Generated by Django 5.1.3 on 2024-12-01 12:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store1', '0005_alter_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
