# Generated by Django 5.1.1 on 2024-11-16 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store1', '0005_remove_product_sub_category_product_sub_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
