# Generated by Django 5.1.2 on 2024-10-26 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store1', '0006_product_all'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='All',
            new_name='ALL',
        ),
    ]
