# Generated by Django 5.1.1 on 2024-11-22 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store1', '0009_subcategory_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='avatar',
        ),
    ]
