# Generated by Django 5.1.1 on 2024-11-20 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store1', '0014_remove_subcategory_category_order_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Country',
        ),
        migrations.RemoveField(
            model_name='order',
            name='location',
        ),
        migrations.RemoveField(
            model_name='product',
            name='alcohol_content',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='origin',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='store1.category'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.CharField(default='Unknown', max_length=155),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(default='Uknown', max_length=15),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category_name',
            field=models.CharField(blank=True, help_text='Manually input the category name if not selecting from the list', max_length=255, null=True),
        ),
    ]
