# Generated by Django 5.1.1 on 2024-11-21 06:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store1', '0016_remove_subcategory_category_product_alcohol_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='category_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='store1.category'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
