# Generated by Django 5.1.1 on 2024-11-21 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store1', '0017_remove_subcategory_category_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='avatar',
        ),
    ]
